name: micropolis
version: '1.0'
icon: micropolis.png
summary: Micropolis, the original city simulation game from Maxis Software
description: |
  Micropolis, the original award winning city simulation game from
  Maxis Software, now runs on powerful Unix workstations with X11!  Now
  it's souped up, and even supports networked multi user collaboration!
  Multi Player Micropolis is designed to be a fun cooperative educational
  experience!

  Micropolis is a colorful animated interactive system simulation
  game, providing a set of rules and tools for planning and building a
  complex dynamic simulated city.  Several people on different X11
  workstations can participate in the same city, cooperating and
  coordinating their actions across the network.

  Working together, you can zone land use, hook up the power grid,
  build roads, bridges, parks and stadiums, raise taxes, and even summon
  disasters, causing the city to grow and thrive, or crumble and die.  It's
  a creative, entertaining way to develop your political skills!

  SimCity designed and implemented by Will Wright,
  Copyright (C) 2002 by Electronic Arts.
  Unix porting, optimization and TCL/Tk user interface design
  by Don Hopkins (dhopkins@DonHopkins.com), for DUX Software.
  Ported to OLPC Fedora Linux by Don Hopkins.

  SimCity, Unix Version.  This game was released for the Unix platform
  in or about 1990 and has been modified for inclusion in the One Laptop
  Per Child program.  Copyright (C) 1989 - 2007 Electronic Arts Inc.

base: core20
grade: stable
confinement: strict

apps:
  micropolis:
    command: bin/micropolis
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/micropolis.desktop
    plugs:
      - audio-playback
      - desktop
      - pulseaudio
      - x11
      - wayland

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  launcher:
    source: launcher
    plugin: dump

  micropolis:
    after: [desktop-glib-only, launcher]
    source: git://git.zerfleddert.de/micropolis
    # source: git://dev.laptop.org/projects/simcity-activity
    source-type: git
    plugin: make
    override-pull: |
      snapcraftctl pull
      sed -i 's|set CityDir .*|set CityDir $env(SNAP_USER_COMMON)|' res/micropolis.tcl
      sed -i 's|^Icon=.*|Icon=/usr/local/share/pixmaps/micropolis.png|' Micropolis.desktop
    override-build: |
      make -C src
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      ln -s paplay $SNAPCRAFT_PART_INSTALL/usr/bin/play
    build-packages:
      - byacc
      - libx11-dev
      - libxext-dev
      - libxpm-dev
    stage-packages:
      - libmagic1
      - libx11-6
      - libxext6
      - libxpm4
      - locales-all
      - pulseaudio-utils
